### ISSUE TITLE
isErrorShown

### ISSUE THREAD

**Issue by web-dave** [workshops-de/angular-rxjs-workshop#1]
@GregOnNet 
ich hab mich schon oft gefragt was hier die Idee war.

https://github.com/workshops-de/angular-rxjs-workshop/blob/24b7e9e477eec1e68220022c64485ef864b7dd98/apps/client/src/app/todos/todos.component.ts#L20

**Comment by GregOnNet** [comment]
Da habe ich mich gestern Nacht auch gefragt.
Ich schau mir das nochmal an.
Vielleicht ist das ein left-over...

**Comment by GregOnNet** [comment]
Fixed in https://github.com/workshops-de/angular-rxjs-workshop/commit/b5dd65f3ac73be09adbe818593e1c3a88ea1de76
